spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: OrderConfirmation:com.a1st.ecom.order.kafka.OrderConfirmation

server:
  port: 8070

application:
  config:
    user-url: http://localhost:8222/api/v1/users
    product-url: http://localhost:8222/api/v1/products
    # TODO: not yet implemented
    payment-url: http://localhost:8222/api/v1/payments