services:
#  postgres:
#    image: postgres
#    container_name: ms-postgres
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_USER: a1st
#      POSTGRES_PASSWORD: a1st
#      PGDATA: /var/lib/postgresql/data/pgdata
#    volumes:
#        - postgres:/var/lib/postgresql/data/pgdata
#    networks:
#        - microservices-network
#    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: ms-mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: a1st
      MONGO_INITDB_ROOT_PASSWORD: a1st
    volumes:
      - mongo:/data
    networks:
      - microservices-network
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    container_name: ms-mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: a1st
      ME_CONFIG_MONGODB_ADMINPASSWORD: a1st
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: a1st
      ME_CONFIG_BASICAUTH_PASSWORD: a1st
    networks:
        - microservices-network
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - 22181:2181
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - microservices-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ms-kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    networks:
      - microservices-network


  mail-dev:
    image: maildev/maildev
    container_name: ms-mail-dev
    ports:
      - 1080:1080
      - 1025:1025


networks:
  microservices-network:
    driver: bridge


volumes:
  postgres:
  mongo: